name: chat_gpt_flutter
description: A new chat  gpt  project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  profile_photo: ^1.0.1
  badges: ^2.0.1
  banner_listtile: ^2.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: 3.2.3
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^0.22.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # avatars
    - assets/Sprite/avatar/avatar_1.png
    - assets/Sprite/avatar/avatar_2.png
    - assets/Sprite/avatar/avatar_3.png
    - assets/Sprite/avatar/avatar_4.png
    - assets/Sprite/avatar/avatar_5.png
    - assets/Sprite/avatar/avatar_6.png
    - assets/Sprite/avatar/avatar_7.png
    - assets/Sprite/avatar/avatar_8.png
    - assets/Sprite/avatar/avatar_9.png
    - assets/Sprite/avatar/avatar_10.png
    - assets/Sprite/avatar/avatar_11.png
    - assets/Sprite/avatar/avatar_12.png
    
    # zodiacs
    - assets/Sprite/zodiac/img_constellation_Aquarius.png
    - assets/Sprite/zodiac/img_constellation_Aries.png
    - assets/Sprite/zodiac/img_constellation_Cancer.png
    - assets/Sprite/zodiac/img_constellation_Capricorn.png
    - assets/Sprite/zodiac/img_constellation_Gemini.png
    - assets/Sprite/zodiac/img_constellation_Leo.png
    - assets/Sprite/zodiac/img_constellation_Libra.png
    - assets/Sprite/zodiac/img_constellation_Pisces.png
    - assets/Sprite/zodiac/img_constellation_Sagittarius.png
    - assets/Sprite/zodiac/img_constellation_Scorpio.png
    - assets/Sprite/zodiac/img_constellation_Taurus.png
    - assets/Sprite/zodiac/img_constellation_Virgo.png

    # taskbar icons
    - assets/Sprite/taskbar/icon_tabbar_card_selected.png
    - assets/Sprite/taskbar/icon_tabbar_card_unselected.png
    - assets/Sprite/taskbar/icon_tabbar_chat_selected.png
    - assets/Sprite/taskbar/icon_tabbar_chat_unselected.png
    - assets/Sprite/taskbar/icon_tabbar_setting_selected.png
    - assets/Sprite/taskbar/icon_tabbar_setting_unselected.png
    - assets/Sprite/taskbar/icon_tabbar_shop_selected.png
    - assets/Sprite/taskbar/icon_tabbar_shop_unselected.png

    # info page
    - assets/Sprite/info/img_encourage.png
    - assets/Sprite/info/img_gem.png
    - assets/Sprite/info/img_nativeshare.png
    - assets/Sprite/info/img_PrivacPolicy.png
    - assets/Sprite/info/img_termsofuse.png
    - assets/Sprite/info/img_contact.png
    - assets/Sprite/info/img_addIcon.png
    - assets/Sprite/info/img_editor.png
    - assets/Sprite/info/discord.png
    - assets/Sprite/info/tiktok.png
    - assets/Sprite/info/img_notsubscribe.png
    # - assets/Sprite/info/img_shopbundle_zuanshi.png

    # purchase page
    - assets/Sprite/purchase/bg_premium.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_01.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_02.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_03.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_04.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_05.png
    - assets/Sprite/purchase/img_gems_gemSlot_shop_06.png
    - assets/Sprite/purchase/img_limitOffer_shop.png
    - assets/Sprite/purchase/img_shopbundle_bg.png
    - assets/Sprite/purchase/icon_singleGem_purple.png
    - assets/Sprite/purchase/img_shopbundle_tag.png
    - assets/Sprite/purchase/img_shop_slot_label.png
    - assets/Sprite/purchase/chat_diamond@1x.png
    - assets/Sprite/purchase/icon_chat_Stopwatch.png
    - assets/Sprite/purchase/shop_image_freeGemsTitle.png
    - assets/Sprite/purchase/shop_image_gemsTItle.png
    - assets/Sprite/purchase/shop_image_offerTitle.png
    - assets/Sprite/purchase/img_bg_shopSlot_blue.png
    - assets/Sprite/purchase/shop_btn_bg_rewardAds.png
    
    # premium page
    - assets/Sprite/premium/bg_primium_large.png
    - assets/Sprite/premium/bg_continue.png
    - assets/Sprite/premium/img_primium_text.png
    - assets/Sprite/premium/icon_right.png

    # no friends list
    - assets/Sprite/no_friends_list/img_bg_roundCorner.png
    - assets/Sprite/no_friends_list/img_chat_nochat.png

    # pick model
    - assets/Sprite/pick_model/avatar_1.png
    - assets/Sprite/pick_model/avatar_2.png
    - assets/Sprite/pick_model/avatar_3.png
    - assets/Sprite/pick_model/avatar_4.png
    - assets/Sprite/pick_model/icon_card_arrow_left.png
    - assets/Sprite/pick_model/icon_card_arrow_right.png
    - assets/Sprite/pick_model/icon_card_isAI.png
    - assets/Sprite/pick_model/img_btn_skip_main.png
    - assets/Sprite/pick_model/img_btn_back_main.png
    - assets/Sprite/pick_model/img_btn_like_main.png
    - assets/Sprite/pick_model/img_card_hand.png
    - assets/Sprite/pick_model/img_card_line_down.png
    - assets/Sprite/pick_model/img_card_line_level.png
    - assets/Sprite/pick_model/bg_priceAndValue.png
    - assets/Sprite/pick_model/bg_gotitButton.png
    - assets/Sprite/pick_model/img_shopbundle_bar.png
    - assets/Sprite/pick_model/icon_card_like_big.png
    - assets/Sprite/pick_model/icon_card_unlike_big.png
    - assets/Sprite/pick_model/profile_btn_dislike_bg.png
    - assets/Sprite/pick_model/profile_bgn_like_bg.png
    - assets/Sprite/pick_model/common_btn_close.png

    # chatpage

    - assets/Sprite/chat_page/img_matchTitle.png
    - assets/Sprite/chat_page/img_match_heart.png
    - assets/Sprite/chat_page/common_btn_back_alpha.png
    - assets/Sprite/chat_page/img_frame_privateInfo.png
    - assets/Sprite/chat_page/img_datting_mateChat_bg.png
    - assets/Sprite/chat_page/img_datting_myChat_bg.png
    - assets/Sprite/chat_page/aichat_slot_thoughtBtn.png
    - assets/Sprite/chat_page/aichat_slot_regenerateBtn.png
    - assets/Sprite/chat_page/aichat_setting_bg.png
    - assets/Sprite/chat_page/aichat_setting_button_unSelected.png
    - assets/Sprite/chat_page/aichat_setting_icon_detailSetting.png
    - assets/Sprite/chat_page/aichat_setting_icon_history.png
    - assets/Sprite/chat_page/aichat_setting_icon_replay.png
    - assets/Sprite/chat_page/aichat_setting_switcher.png
    - assets/Sprite/chat_page/aichat_slotName_bg.png
    - assets/Sprite/chat_page/aichat_slotl_bg.png
    - assets/Sprite/chat_page/aichat_textslot_animatDot.png
    - assets/Sprite/chat_page/aichat_slot_thoughtBtn.png
    - assets/Sprite/chat_page/aichat_userinput_bg.png
    - assets/Sprite/chat_page/alert_icon.png
    - assets/Sprite/chat_page/img_datting_mateChat_bg.png
    - assets/Sprite/chat_page/img_datting_myChat_bg.png
    - assets/Sprite/chat_page/aichat_userinput_sendBtn.png
    - assets/Sprite/chat_page/aichat_history_reset.png
    - assets/Sprite/chat_page/aichat_profile_button.png





    # giftbox
    - assets/Sprite/img_btn_gift_main.png


 
    


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalloThambi2-Regular
      fonts:
        - asset:  assets/Font/BalooThambi2-Regular.ttf
        # - assets/Font/Anton.ttf
    # - assets/Font/Arial Black.ttf
    # - assets/Font/Arial.ttf
    # - assets/Font/BalooThambi2-Bold.ttf
    # - assets/Font/BalooThambi2-ExtraBold.ttf
    # - assets/Font/BalooThambi2-Medium.ttf
        # - assets/Font/BalooThambi2-Regular.ttf
    # - assets/Font/BalooThambi2-SemiBold.ttf
    # - assets/Font/Bangers.ttf
    # - assets/Font/BalooThambi2-Regular.ttf
    # - assets/Font/BalooThambi2-Regular.ttf
    # - assets/Font/BalooThambi2-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  image: assets/Sprite/bg_loading.png